### PR TITLE
Fr translation

### PR DESCRIPTION
**Pull request by fiorellabgs**
## Content

A contribution to help to translate the documentation in French, started here :  https://github.com/italia/publiccode.yml/pull/73. I'm focusing on schema.core.rst. 
As it is, the document is partially translated. 

## Review

- [ ] Ensure your files are written following RST specs (*not MD!*)
- [ ] Italian version
- [ ] English version
- [ ] Example files 
- [ ] Ask for review

### CODE REVIEW

**Comment by libremente** [comment]
Hi @fiorellabgs and thanks a lot for your contribution! We will review this and provide you some feedback ASAP. 👍

**Comment by ruphy** [comment]
Amazing!!!

**Comment by bzg** [comment]
Hi @ruphy - can I help getting this PR merged? @fiorellabgs and I would like to continue working on this together, possibly with @nclsppr, the merge would help a lot. Thanks!

**Comment by ruphy** [comment]
Hi,

Bien sûr! I will look into it tomorrow first thing in the morning.

Riccardo

**Comment by ruphy** [comment]
The first version is in! Thanks a lot! :tada:

I merged this instead of #73 as it looked to me like more complete and you mentioned you are working with @nclsppr. Can you coordinate so I can close #73 ?

I will now set aside some hours to work on the translation infrastructure, the more the project develops, the more I fear the translations will diverge. See for example this issue: https://github.com/italia/publiccode-editor/issues/92

**Comment by bzg** [comment]
> I merged this instead of #73 as it looked to me like more complete and you mentioned you are working with @nclsppr. Can you coordinate so I can close #73 ?

To be clear, we didn't plan to coordinate with @nclsppr but I'll work on this. More precisely, I'll review #73 and see if it is mergeable or if I can help rework it.

> I will now set aside some hours to work on the translation infrastructure, the more the project develops, the more I fear the translations will diverge. See for example this issue: italia/publiccode-editor#92

Yes, i18n is always a challenge - let us know if we can help!

**Pull request merged**
